### ISSUE TITLE
ASP.NET Core?

### ISSUE THREAD

**Issue by thc-aarsleff** [microsoftgraph/aspnet-connect-sample#11]
Any chance that you can make an example on how to connect and query Graph using .Net Core?

**Comment by DianeD** [comment]
Hi @thc-aarsleff . Thanks for the feedback! This is in our app ideas list. We should have an ASP.NET Core version of another sample soon that shows how to connect and query Microsoft Graph. Closing this issue now but will add a comment when it's public.
