### ISSUE TITLE
Problem in authentication: change authentication URL

### ISSUE THREAD

**Issue by lorenzosoncini** [microsoftgraph/aspnet-connect-sample#15]
We have registered 2 different app one for development and one for production. We use only the authentication and send mail functionality.
In my test application I have some trouble in logon (we have received some "response_type 'token' is not supported for the application" and "unsupported_response_type". 
Like explained in this article
https://docs.microsoft.com/en-gb/azure/active-directory/develop/active-directory-v2-protocols-oauth-code
we have:
1 - Add in web config the appsettings "ida:AppTenancy"  with value as our tenancy domain
2 - Changed the the "Authority" property of the "OpenIdConnectAuthenticationOptions" in the method public void ConfigureAuth(IAppBuilder app) with the code:
Authority = string.Format("https://login.microsoftonline.com/{0}/v2.0",appTenancy),

For now its work.
LSo

**Comment by jamescro** [comment]
I'm not sure I see the issue with this sample specifically. Have you had to implement auth a little differently because of your own requirements?
