### ISSUE TITLE
Stuck on login screen

### ISSUE THREAD

**Issue by nukec** [microsoftgraph/aspnet-connect-sample#19]
I got stuck on login screen. Even after log in, when I press get email, I get redirected to login screen again, and it loops few times before I receive error in app:

> Microsoft Graph Connect sample for ASP.NET 4.6
> An error occurred while processing your request.
> unsupported_response_type

**Comment by jamescro** [comment]
I can't reproduce this. The error you're getting suggests that there's a problem with your client's configuration. Did you register it at apps.dev.microsoft.com, and did you configure it as a web application?

**Comment by nukec** [comment]
I used sample, created app on apps.dev.microsoft.com I can see them there on the list, then I use key and application id and try to login with my organisation email. Every single time, it just redirects back to login screen.

**Comment by jamescro** [comment]
When you added the web platform and the key, did you save your updates? I've missed that step in the past and gotten clients that don't work until I save the updates. 
Also, have you tried with different browsers? 
Are you using an O365 tenant account?

**Comment by nukec** [comment]
I think it is broken out of the box. Here is recording @jamescro http://recordit.co/73sqTHeujI

**Comment by jamescro** [comment]
Your client and configuration all appear to be correct. Given the popup warning you are seeing, it looks like your browser's security settings are breaking the authentication flow. Have you tried this with a different browser client?
Also, could you try that same client and secret with this sample:

https://github.com/microsoftgraph/aspnet-connect-rest-sample

It's a REST-based version of this sample that uses a different authentication library. I'd like to see if you if you have the same problem with that one.

**Comment by nukec** [comment]
It works in IE, doesn't work in Firefox and Chrome.

**Comment by nukec** [comment]
Ok so I am going to work IE. I am using organisation's Active Directory, which means I have limited access to do write and read. I've created new active directory there and assigned user to it. App is registered under same active directory, and when settings set up under web.config I get unauthoirzed_client aftertrying to login. Can I use additional active directory if it is not default directory under organisation account?

**Comment by jamescro** [comment]
Thanks for the follow-up. I'll see if I can find an answer to your latest question.

**Comment by jamescro** [comment]
You'll need to register the app under the new active directory.

**Comment by busbina** [comment]
Was there ever a fix for this on Chrome? I am guessing Chrome does not like to redirect to localhost from outside.  Trying to find some kind of docs on it. Also mine is working fine in IE.

**Comment by busbina** [comment]
Got it, Chrome was respecting the header "no-referrer-when-downgrade", and because we were going from https to http, it was refusing to redirect. I switched the redirect Uri to https://localhost:44300 in both the web.config and the app registration. Had to choose the allow unsafe connections but it worked.
