### ISSUE TITLE
HttpContext Session is null

### ISSUE THREAD

**Issue by gt-downunder** [microsoftgraph/aspnet-connect-sample#23]
I've implemented this code exactly as provided and am successfully authenticating against Azure Active Directory. I'm able to access the claims of the logged in user and see no issues there.

However, I'm getting an object reference exception when trying to use Graph in the **SessionTokenCache.cs** file where the _httpContext.Session_ is null.  

Why would this be?  My web.config already contains _runAllManagedModulesForAllRequests="true"_ in the modules section.  I'm lost.

![image](https://user-images.githubusercontent.com/12604549/27008640-bdd7d564-4e2b-11e7-8dc8-182dc4767a91.png)

**Comment by jamescro** [comment]
I'm not sure what is going wrong here, but could you try this sample and see if you run into the same trouble there? https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-v2
The session token cache in this sample is based on the one in that sample.

**Comment by jamescro** [comment]
Resolving for now. Please let us know if this problem continues, especially if it isn't repeatable in the samle from the Azure-Samples organization.
