### ISSUE TITLE
The SDKHelper graph client cache does not

### ISSUE THREAD

**Issue by dotnetgator** [microsoftgraph/aspnet-connect-sample#24]
Note that the graph client instance is being generated new every time - the private static "graphClient" variable is never used.  As a consequence, the SignOutClient method does nothing.

**Comment by jamescro** [comment]
Thanks for pointing this out. That private variable is a vestige of an older pattern that checked for the existence of a client before creating a new one. The idea was to save a bit of performance cost. I could restore the check for the existence of a previously created client, but before I do that I'd like to follow up with our engineers to see just how much of a performance improvement this gives us.

**Comment by jamescro** [comment]
I've removed the unused graphClient variable and the SignOutClient method.
