### ISSUE TITLE
 An error occurred while processing your request.  unauthorized_client

### ISSUE THREAD

**Issue by Newgit-hubber** [microsoftgraph/aspnet-connect-sample#25]
No matter what i sign in with, the global admin or the user, it is throwing into the error page with error:
Unauthorized_client

**Comment by jamescro** [comment]
Did you register your client here? https://apps.dev.microsoft.com/
Also, did you add the web platform and save your changes? Sometimes it's not clear that you have to save any updates you make to your client.

**Comment by jamescro** [comment]
Closing for now. Please reopen if this is still an issue.
