### ISSUE TITLE
Group membership

### ISSUE THREAD

**Issue by Pelago** [microsoftgraph/aspnet-connect-sample#28]
Hi, I have tried to alter some of your and a lot of others code samples to be able to get back a list of group displayName's the user is a member of, but with no luck. 

I know this is not a part of your sample application but still i need to ask you for guidance to get user group membership. I have tried since Build Conference to find out a way to get a list of Group names the user is member of and this sample has been one of the few found that is working querying the Graph API's. Hope you could share some solution or point me in the right direction
  
Just altering the endpoint in, for instance a copy of, the GetMyEmailAdress() function with 

string endpoint = "https://graph.microsoft.com/v1.0/me/memberOf"; 
string queryParameter = "?$select=displayName";
and added Group.Read.All in the application settings in the Application Registration Portal.

does not do the trick!

the responce is instead of a successfull one
"
{StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  request-id: {Erased by me}
  client-request-id: {Erased by me}
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceB","ScaleUnit":"000","Host":"AGSFE_IN_6","ADSiteName":"AMS"}}
  Duration: 93.3856
  Cache-Control: private
  Date: Sun, 22 Oct 2017 14:49:59 GMT
  Content-Type: application/json
}}
"
and the responce.IsSuccessStatusCode = false.

I expected to get some Json back, since this string works perfectly in Graph Explorer
https://graph.microsoft.com/v1.0/me/memberOf?$select=displayName

Any clarification on this matter would be appreciated
Best Regards
/Patrik

**Comment by jamescro** [comment]
You are likely getting that error because your application doesn't have the necessary permission. In order to read group data, you need to set the Group.Read.All permission scope. Only admin users can consent to that scope, though. 

Take a look at this topic on Microsoft Graph permissions: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference
