### ISSUE TITLE
Register application - Allow Implicit Flow - Can't Set

### ISSUE THREAD

**Issue by BinLiuPremera** [microsoftgraph/aspnet-connect-sample#29]
The documented steps under "Register the application" could not be followed through with success. At step 3, clicking on the ONLY active button, 'Edit in the Azure Portal', takes me to Azure portal for the newly created application (under Azure Active Directory), which is fine. There I could generate a key (and record the secret), but nowhere I could find UI controls/links/buttons to do steps 6-8 (Platform, Allow Implicit Flow). 

Without that (and I did manually grant Microsoft Graph API explicit rights for app and user), the application simply returned 'unauthorized_client' after going through 'Sign in with Microsoft'.

**Comment by jamescro** [comment]
Thanks for the feedback. I can't reproduce the issue. 

Are you using this registration portal?
https://apps.dev.microsoft.com/

And after you click "Add an app" are you seeing this page?

![image](https://user-images.githubusercontent.com/6666618/33583033-1a979e1c-d90d-11e7-86e9-eaaa95920328.png)

**Comment by BinLiuPremera** [comment]
This is what I get after clicking on 'Add an app' at https://apps.dev.microsoft.com 
![capture](https://user-images.githubusercontent.com/34255137/33610400-4e00dba6-d980-11e7-9e2f-7d2b22badb21.JPG)

**Comment by BinLiuPremera** [comment]
I'm able to get through all the steps and get the app to work. Thanks Jim!

**Comment by jamescro** [comment]
Thanks for sharing your experience with the registration portal. We'll see if we can alleviate the confusion you faced.
