### ISSUE TITLE
Get email address not working

### ISSUE THREAD

**Issue by Kagigz** [microsoftgraph/aspnet-connect-sample#37]
Hello,

I'm having issues trying to get this sample to work.
I can login with my microsoft account, but when I click on "Get email address", I get a resource not found message.
The url the app is trying to call is /Home/GetMyEmailAddress.

Moreover, when I first tried to build the project, there was an error saying that "SDK Helper was not found", so I found a SDK Helper file somewhere else but the AccountController.cs file needed the SignOutClient() function to work properly. I just commented this line to test the other features without testing the signing out, but it would be nice to figure out how to get this to work.

Thanks

**Comment by jasonjoh** [comment]
Sorry for the trouble @Kagigz. I just cloned this repo and tried to reproduce the problems you've reported and could not. However I know we point folks to this sample multiple ways, so I'm wondering if one of those ways skips a step or points to broken code.

Did you:

- Download or clone this repository directly from GitHub and use the [./Microsoft Graph SDK ASPNET Connect/Microsoft Graph SDK ASPNET Connect.sln]([./Microsoft Graph SDK ASPNET Connect/Microsoft Graph SDK ASPNET Connect.sln] solution?
- Get here from https://developer.microsoft.com/graph/docs/concepts/aspnetmvc, and use the [./Microsoft Graph SDK ASPNET Connect/Microsoft Graph SDK ASPNET Connect.sln]([./starter-project/Microsoft Graph SDK ASPNET Connect.sln] solution?
- Download a preconfigured ZIP file from https://developer.microsoft.com/graph/quick-start?

**Comment by jasonjoh** [comment]
I suspect that you're using the starter-project version? The files in there require extra work to get going, you need to follow the steps in https://developer.microsoft.com/graph/docs/concepts/aspnetmvc.

Alternatively you can just use the finished project in the "Microsoft Graph SDK ASPNET Connect" folder (you still need to add your client ID and secret in web.config).
