### ISSUE TITLE
Invalid_Request Error

### ISSUE THREAD

**Issue by Feryllium** [microsoftgraph/aspnet-connect-sample#38]
Dear Team

Firstly, I'd like to thank you for the great guide.

How to reproduce:
1) Instead of registering the app in the link provided - I registered the app in the Azure Portal. I made a Key and made that my app secret. I also changed the manifest to allow multi tenant log in. 
2) All the rest I followed like in the guide.

I'm trying to learn how to use the Microsoft Graph API in order to manage users on multiple azure subscriptions. I'll be developing a small ASP.NET web application which will help me have a better sight on things.

Below is a screenshot of the error:
![image](https://user-images.githubusercontent.com/15891370/45024324-0a771180-b039-11e8-8c9b-666baf6ac151.png)

Thank you in advance

**Comment by jasonjoh** [comment]
> Instead of registering the app in the link provided - I registered the app in the Azure Portal. I made a Key and made that my app secret. I also changed the manifest to allow multi tenant log in.

That's the problem. Azure Portal registrations are not compatible with the MSAL auth library used in this sample. You MUST register in https://apps.dev.microsoft.com. **Additionally**, if when you login to https://apps.dev.microsoft.com, you see more than one **Add an app** button, you MUST select then one that corresponds to **Converged apps**.
